# Generated by Django 5.2.13 on 2026-05-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lecture',
        ),
        migrations.AddField(
            model_name='student',
            name='lecture',
            field=models.ManyToManyField(related_name='students', through='lectures.LectureStudent', to='lectures.lecture'),
        ),
    ]
