# Generated by Django 5.2.13 on 2026-04-30 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lectures.professor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lectures.lecture'),
            preserve_default=False,
        ),
    ]
