# Generated by Django 6.0.4 on 2026-04-30 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_lecture_professor_student_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lectures.lecture'),
        ),
    ]
