# Generated by Django 5.2.13 on 2026-04-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('stdnum', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
